### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by kuboco** [yks72p/vk_album_downloader#12]
When I run Python script, has an error:
```
number of albums to download: 1
downloading album: Дельфин _ Эрарта _ 19.12.2015 (Спб)
Traceback (most recent call last):
  File "C:\Users\ducnv\OneDrive\Desktop\vk_album_downloader-master\vk_album_downloader.py", line 156, in <module>
    main()
  File "C:\Users\ducnv\OneDrive\Desktop\vk_album_downloader-master\vk_album_downloader.py", line 148, in main
    download_image(largest_image_src, album_path + '/' +
  File "C:\Users\ducnv\OneDrive\Desktop\vk_album_downloader-master\vk_album_downloader.py", line 78, in download_image
    with open(local_file_name, 'wb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'vk_downloaded_albums/Дельфин _ Эрарта _ 19.12.2015 (Спб).copy_2022-11-28_06-02-04/392477623.jpg?size=1280x853&quality=96&sign=4f85d5ac167b9384b8d02aff2c113b6b&c_uniq_tag=AZz3tDTLhmjN-ReOQCA1Eyk74Zp0eFZp8u-TRaSD7RQ&type=album'
```

Can you help me to solve it?
Thank you.

**Comment by navalnica** [comment]
Hi! The script was written long time ago for Linux. Back then I did not know about `os.path.join` function that concatenates paths in a platform-independent way.

Probably your issues is caused by the use of `/` in paths. Windows uses backslash `\` as a path separator instead of `/` as in Linux.

Try to replace `/` with `\` in paths

**Comment by kuboco** [comment]
Replace "str(p['id']) + extension)" to "str(p['id']) + re.sub("\?.*", "", extension))"
work for me, thanks
